### ISSUE TITLE
Data Model

### ISSUE THREAD

**Issue by MegaMarkHarris** [murmurco/data_storyteller#1]
@mknowlton 

So this is the basic data model I'm working with. I think this will satisfy both HonestX and Fat Larry.

In a way, both of these are dependent on us asking a question:
HonestX: How dirty are you?
Fat Larry: Did Castellucci orchestrate the murder?

We don't have to say these out loud, but it seems like these might be necessary for the calculations. Man, I wish I'd paid more attention in Math!

HonestX:
Question: Which porn star are you+Response: Dirk Diggler.
Metadata: kink=3, confidence=10,dick_size=9. 

Fat Larry: 
Question: Castellucci took out a key man insurance policy+Response:Relevant.
Metadata: castellucci_guilt_factor=7,dongo_innocence_factor=5

Tables:
Table: user (knowlton)
uuid
token

Table: response_metadata
question_key (your_spirit_animal) 
response_key (burt_reynolds)
metadata_key (kink_factor)
metadata_value (2)
metadata_weight-> maybe to determine how important a trait is in the overall calculation

Table: question_response
user_id (knowlton)
question_key (your_spirit_animal)
response_key (burt_reynolds)

overall_response_factor = kink_factor + mustache_factor

Table: content_response
metadata_key (overall_response_factor)
metadata_range_min (4)
metadata_range_max (12)
content_id
content_order -> may not matter for HonestX

Table: content
id
content_uri

Then the algorithm looks up all of my responses, and uses those to figure out my overall_response_factor.

Then, we have a bunch of images in the database, tagged with ranges for each overall_response_factor. That forms my sex queue.

I will likely make your voting on the Sex Queue another "question" and "response". So I'll need a way to indicate something like a "Topic" over top of the "Question"...

For Fat Larry, it looks like this:
Table: response_metadata
question_key (1_3) 
response_key (swipe_right)
metadata_key (dongo_innocence_factor)
metadata_value (2)
metadata_weight-> maybe to determine how important a trait is in the overall calculation

question_key (1_3) 
response_key (swipe_right)
metadata_key (pownall_jerk_factor)
metadata_value (5)

Table: question_response
user_id (knowlton)
question_key (1_3)
response_key (swipe_right)

overall_response_factor = pownall_jerk_factor + dongo_innocence_factor

Table: content_response
metadata_key (overall_response_factor)
metadata_range_min (4)
metadata_range_max (12)
content_id
content_order

So we look up all with overall_response_factor in this range, and send them back. In the case of HonestX, this would mean all, so we can make your sex queue. In the case of Fat Larry, we can maybe just have one assigned to each range, with an order. So each order might have multiple episodes, each with a different overall_response_factor.

**Comment by HollywoodHal** [comment]
Looks good to me. Dick_Size...nice.

On Wed, Apr 8, 2015 at 9:23 PM, Mark Harris <notifications@github.com>
wrote:

> @mknowlton <https://github.com/mknowlton>
>
> So this is the basic data model I'm working with. I think this will
> satisfy both HonestX and Fat Larry.
>
> Basically just match user+question+response. Responses are all
> preprogrammed in these cases, meaning the user is never really typing in
> free form text.
>
> So for Fat Larry, a "question" is a card and a response is a swipe.
>
> For HonestX, a question is say "Which celebrity are you?" and response is
> the one they chose.
>
> user_id
> id
> uuid
> token
>
> question
> id
> question_key ->matching a value in the spreadsheet
> text
>
> response
> id
> response_key ->Matches some id we have in the spreadsheet
> text
>
> response_metadata -> one to many mapping of any number of metadata values
> per response. These feed into the algorithms. The algorithm then will then
> look these up and decide how to use them to serve up the Sex Queue / Serve
> up the next Fat Larry Ep.
>
> HonestX:
> Question: Which porn star are you+Response: Dirk Diggler.
> kink=3, confidence=10,dick_size=9.
>
> Fat Larry:
> Question: Castellucci took out a key man insurance
> policy+Response:Relevant.
> castellucci_guilt_factor=7,dongo_innocence_factor=5
>
> id
> question_id
> response_id
> metadata_key
> metadata_value
>
> question_response ->who responded to what
> id
> user_id
> question_id
> response_id
>
> Let me know if you see any glaring omissions.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/murmurco/data_storyteller/issues/1>.
>



-- 
--------------------------
Murmur <http://www.murmurco.com/>


--------------------------
Mike Knowlton
Partner

O: 646 397 7191
C: 908-884-6004
mike@murmurco.com
<mike@murmurco.com>twitter: @murmurco <http://twitter.com/#!/murmurco>
